# email_service/sender.py

import smtplib
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv

load_dotenv()


def format_email_body(meeting_title: str, insights: dict) -> str:
    """Format meeting insights as readable email."""

    # Action items
    action_items_text = ""
    for item in insights.get("action_items", []):
        task = item.get("task", "")
        owner = item.get("owner", "UNKNOWN")
        deadline = item.get("deadline", "UNKNOWN")
        action_items_text += f"\n  • {task}"
        if owner != "UNKNOWN":
            action_items_text += f" → Owner: {owner}"
        if deadline != "UNKNOWN":
            action_items_text += f" | By: {deadline}"

    # Decisions
    decisions_text = "\n".join(
        [f"  • {d}" for d in insights.get("decisions", [])]
    ) or "  None recorded"

    # Open questions
    questions_text = "\n".join(
        [f"  • {q}" for q in insights.get("open_questions", [])]
    ) or "  None"

    # Topics
    topics_text = ", ".join(insights.get("topics", [])) or "General"

    body = f"""
MEETING SUMMARY — {meeting_title}
{"="*50}

SUMMARY:
{insights.get("summary", "No summary available")}

TOPICS DISCUSSED:
{topics_text}

KEY DECISIONS:
{decisions_text}

ACTION ITEMS:
{action_items_text or "  None recorded"}

OPEN QUESTIONS:
{questions_text}

PARTICIPANTS:
{", ".join(insights.get("participants", []))}

ESTIMATED DURATION:
{insights.get("meeting_duration_estimate", "Unknown")}

{"="*50}
Generated by Meeting Intelligence System
Built by Sandhiya BK | Kamaraj College of Engineering
"""
    return body


def send_meeting_summary(
    recipient_email: str,
    meeting_title: str,
    insights: dict
) -> dict:
    """
    Send formatted meeting summary via Gmail SMTP.
    """
    sender = os.getenv("EMAIL_ADDRESS")
    password = os.getenv("EMAIL_APP_PASSWORD")
    print("EMAIL =", repr(sender))
    print("PASSWORD =", repr(password))

    if not sender or not password:
        return {
            "success": False,
            "error": "Email credentials not configured in .env"
        }

    subject = f"Meeting Summary: {meeting_title}"
    body = format_email_body(meeting_title, insights)

    msg = MIMEMultipart()
    msg['From'] = sender
    msg['To'] = recipient_email
    msg['Subject'] = subject
    msg.attach(MIMEText(body, 'plain'))

    try:
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
            server.login(sender, password)
            server.sendmail(sender, recipient_email, msg.as_string())

        print(f"Email sent successfully to {recipient_email}")
        return {"success": True, "recipient": recipient_email}

    except smtplib.SMTPAuthenticationError:
        return {
            "success": False,
            "error": "Gmail authentication failed. Check App Password in .env"
        }
    except Exception as e:
        return {
            "success": False,
            "error": str(e)
        }


# Test directly
if __name__ == "__main__":
    test_insights = {
        "summary": "Team discussed Q3 budget increase for marketing.",
        "decisions": ["Increase marketing budget by 20%"],
        "action_items": [
            {
                "task": "Prepare budget proposal",
                "owner": "Rahul",
                "deadline": "Thursday"
            }
        ],
        "open_questions": ["Q4 targets not yet discussed"],
        "topics": ["Budget", "Marketing", "Q3 Review"],
        "participants": ["SPEAKER_00", "SPEAKER_01"],
        "meeting_duration_estimate": "10 minutes"
    }

    result = send_meeting_summary(
        recipient_email="bksandhiya17@gmail.com",
        meeting_title="Q3 Budget Review",
        insights=test_insights
    )
    print(result)